name: Flyway Migrate

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'terraform/scripts/**'

env:
  AWS_REGION: af-south-1

jobs:
  migrate:
    name: Run Flyway Migrations
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::229582503298:role/GitHubActionsOIDCRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS access
        run: |
          aws sts get-caller-identity
          aws s3 ls s3://innerlens-website-path-s3-bucket/ || echo "Cannot list bucket contents"

      - name: Setup and initialize Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init and Output
        run: |
          cd terraform
          terraform init
          terraform output

      - name: Extract Terraform Outputs
        uses: dflook/terraform-output@v1
        id: tf-outputs
        with:
          path: terraform

      - name: Print Terraform Outputs (Debug)
        run: |
          echo "RDS Endpoint: ${{ steps.tf-outputs.outputs.rds_endpoint }}"

      - name: Install PostgreSQL Client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run Flyway Migration
        run: |
          flyway -url=jdbc:postgresql://${{ steps.tf-outputs.outputs.rds_endpoint }}/innerlens_website_db \
                 -user=${{ env.DB_USER }} \
                 -password=${{ env.DB_PASS }} \
                 -locations=filesystem:terraform/scripts \
                 migrate


